# Generated by Django 4.1.7 on 2023-03-29 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlistMainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlistMainModel_owner', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(related_name='wishlistMainModel_products', to='accounts.accountsusercartproductmodel')),
            ],
        ),
    ]
