# Generated by Django 4.1.7 on 2023-03-29 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicleMainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('vehicle_no', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('RUNNING', 'RUNNING'), ('BREAKDOWN', 'BREAKDOWN')], max_length=20)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='vehicleBreakdownModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('BREAKDOWN', 'BREAKDOWN'), ('INSPECTION', 'INSPECTION'), ('ASSIGNED', 'ASSIGNED'), ('REPAIR', 'REPAIR'), ('COMPLETED', 'COMPLETED')], max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicleBreakdownModel_owner', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicleBreakdownModel_vehicle', to='vehicle.vehiclemainmodel')),
            ],
        ),
        migrations.CreateModel(
            name='vehicleBreakdownInpectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('INSPECTION', 'INSPECTION'), ('REPAIR', 'REPAIR')], max_length=20)),
                ('breakdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicleBreakdownInpectionModel_breakdown', to='vehicle.vehiclebreakdownmodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicleBreakdownInpectionModel_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='vehicleBreakdownImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('status', models.CharField(choices=[('BREAKDOWN', 'BREAKDOWN'), ('INSPECTION', 'INSPECTION'), ('REPAIR', 'REPAIR')], max_length=20)),
                ('breakdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicleBreakdownImageModel_breakdown', to='vehicle.vehiclebreakdownmodel')),
            ],
        ),
        migrations.CreateModel(
            name='vehicleBreakdownAssignedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakdown', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicleBreakdownAssignedModel_breakdown', to='vehicle.vehiclebreakdownmodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicleBreakdownAssignedModel_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
