# Generated by Django 4.1.7 on 2023-03-29 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderMainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('OUT FOR DELIVERY', 'OUT FOR DELIVERY'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], max_length=40)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderMainModel_owner', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(related_name='orderMainModel_products', to='accounts.accountsusercartproductmodel')),
            ],
        ),
    ]
